version: '3'

services:

  result:
    build: ./result
    ports:
      - "5858:80"
    depends_on:
      - redis
      - db

  vote:
    build: ./vote
    ports:
      - "5000:80"
    depends_on:
      - redis
      - db

  vote-1:
    build: ./vote
    ports:
      - "5001:80"
    depends_on:
      - redis
      - db

  worker:
    build: ./worker
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379"
  
  db:
    image: postgres:9.4
    container_name: db
    volumes: 
    - "db-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  db-data: {}